"""
Agent Schemas - Request/Response models for agent operations
"""

from typing import Any

from pydantic import BaseModel, Field, field_validator


class ConversationMessage(BaseModel):
    """Single message in a conversation."""

    role: str = Field(..., description="Message role: 'user' or 'assistant'")
    content: str = Field(..., description="Message content")


class NextQuestionRequest(BaseModel):
    """Request to generate the next question for the agent."""

    conversation_history: list[ConversationMessage] = Field(
        ..., description="Previous conversation messages"
    )
    user_context: dict[str, str] | None = Field(
        default=None,
        description="Optional user context (name, bio, age, etc.). "
        "Values can be strings or integers (e.g., age: 28 or age: '28'). "
        "All values are normalized to strings internally.",
    )

    @field_validator("user_context", mode="before")
    @classmethod
    def normalize_user_context(cls, v: Any) -> dict[str, str] | None:
        """
        Normalize user_context values to strings.

        Accepts both string and integer values (e.g., age: 28 or age: "28")
        and converts all values to strings for consistent internal representation.

        This validator runs before type validation, allowing flexible input types
        while ensuring the final model always has string values.

        Args:
            v: Raw user context dict with str or int values, or None

        Returns:
            Normalized dict with all string values, or None if input is None

        Examples:
            >>> normalize_user_context({"age": 28, "name": "Juan"})
            {"age": "28", "name": "Juan"}
            >>> normalize_user_context({"age": "28", "name": "Juan"})
            {"age": "28", "name": "Juan"}
        """
        if v is None:
            return None

        if not isinstance(v, dict):
            return v  # Let Pydantic handle the type error

        normalized: dict[str, str] = {}
        for key, value in v.items():
            # Convert int/float to str, keep str as-is
            if isinstance(value, (int, float)):
                normalized[key] = str(value)
            elif isinstance(value, str):
                normalized[key] = value
            else:
                # For other types, convert to string
                normalized[key] = str(value)

        return normalized


class NextQuestionResponse(BaseModel):
    """Response containing the next question generated by the agent."""

    question: str = Field(..., description="Generated next question")
    reasoning: str | None = Field(
        default=None, description="Optional reasoning for the question"
    )

